// RabiaRashid/Angular/RecipeBook/src/app/recipes/recipe-list/recipe-item/recipe-item.component.ts
import { Component, OnInit,Input } from '@angular/core';
import { Recipe } from '../../recipe.model';
import { RecipeService } from '../../recipe.service';

@Component({
  selector: 'app-recipe-item',
  templateUrl: './recipe-item.component.html',
  styleUrls: ['./recipe-item.component.css']
})
export class RecipeItemComponent implements OnInit {
recipe:Recipe;
@Input() index:Number;
  constructor(private recService:RecipeService) { }

  ngOnInit() {
    this.recipe=this.recService.getRecipeByIndex(this.index);
  }

}

<a class="list-group-item clearfix" style="cursor:pointer" [routerLink]="[index]" routerLinkActive="active">
  <div class="float-left">
    <h4 class="list-group-heading">{{recipe.name}}</h4>
    <p class="list-group-text">{{recipe.desc}}</p>
  </div>
  <span class="float-right">
    <img [src]="recipe.imgPath" alt="{{recipe.name}}" class="img-fluid" style="max-height: 50px;">
  </span>
</a>

// RabiaRashid/React/RecipeBookApp/src/components/recipe-item-component.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';

export default (props) => {
    return(
        <Link className="list-group-item clearfix" to={`/recipes/${props.index}`}>
            <div className="float-left">
                <h4 className="list-group-heading">{props.recipe.name}</h4>
                <p className="list-group-text">{props.recipe.desc}</p>
            </div>
            <span className="float-right">
                <img className="img-fluid" style={{maxHeight: '50px'}} src={props.recipe.imgPath}/>
            </span>
        </Link>
    );
}
